apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: moneymanager
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s-service
spec:
  selector:
    app: spring-boot-k8s
  type: NodePort   # oder ClusterIP/LoadBalancer je nach Bedarf
  ports:
     - protocol: "TCP"
       port: 8080          # Port im Cluster
       targetPort: 8080    # Port des Containers
       nodePort: 30080     # Nur relevant bei NodePort, extern erreichbar
